# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170528_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next_post_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='next_post_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
