# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_next_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='next_post_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='next_post_url',
        ),
    ]
