# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='fb_url',
            field=models.URLField(default='https://vk.com/yuraist'),
        ),
        migrations.AlterField(
            model_name='info',
            name='in_url',
            field=models.URLField(default='https://instagram.com/yuraist'),
        ),
        migrations.AlterField(
            model_name='info',
            name='tw_url',
            field=models.URLField(default='https://twitter.com/yuraist'),
        ),
        migrations.AlterField(
            model_name='info',
            name='vk_url',
            field=models.URLField(default='https://www.facebook.com/yuraistom'),
        ),
    ]
